name: Main

on:
  push:
    branches: [main]
  pull_request:

env:
  CACHE: true

jobs:
  filter:
    name: Detect Workspace Members
    runs-on: ubuntu-latest
    outputs:
      members: ${{ steps.parse.outputs.members }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          cargo-cache-key: cargo-filter-workspace

      - name: Parse workspace
        id: parse
        run: pnpm tsx ./scripts/setup/members.mts

  process:
    name: Package
    needs: filter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        member: ${{ fromJson(needs.filter.outputs.members) }}
    outputs:
      crate: ${{ steps.changes.outputs.crate }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Detect Changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            crate:
              - '${{ matrix.member }}/**'

      - name: Setup Environment
        uses: ./.github/actions/setup
        if: ${{ steps.changes.outputs.crate == 'true' }}
        with:
          cargo-cache-key: cargo-${{ matrix.member }}
          toolchain: build, format, lint, test
          solana: true

      - name: Audit
        if: ${{ steps.changes.outputs.crate == 'true' }}
        run: pnpm audit ${{ matrix.member }}

      - name: Format
        if: ${{ steps.changes.outputs.crate == 'true' }}
        run: pnpm format ${{ matrix.member }}

      - name: Lint / Clippy
        if: ${{ steps.changes.outputs.crate == 'true' }}
        run: pnpm lint:clippy ${{ matrix.member }}

      - name: Lint / Docs
        if: ${{ steps.changes.outputs.crate == 'true' }}
        run: pnpm lint:docs ${{ matrix.member }}

      - name: Lint / Features
        if: ${{ steps.changes.outputs.crate == 'true' }}
        run: pnpm lint:features ${{ matrix.member }}

      - name: Build (sbf)
        if: ${{ steps.changes.outputs.crate == 'true' }}  
        run: pnpm build ${{ matrix.member }}

      - name: Test
        if: ${{ steps.changes.outputs.crate == 'true' }}
        run: pnpm test ${{ matrix.member }}
