name: Main

on:
  push:
    branches: [main]
  pull_request:

env:
  CACHE: true

jobs:
  filter:
    name: Filter workspace
    runs-on: ubuntu-latest
    outputs:
      members: ${{ steps.parse.outputs.members }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          cargo-cache-key: cargo-filter-workspace

      - name: Parse workspace
        id: parse
        run: pnpm tsx ./scripts/setup/members.mts

  process:
    name: Process
    needs: filter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        member: ${{ fromJson(needs.filter.outputs.members) }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          cargo-cache-key: cargo-${{ matrix.member }}
          toolchain: build, format, lint, test

      - name: Format
        run: pnpm format ${{ matrix.member }}

      - name: Lint / Clippy
        run: pnpm lint:clippy ${{ matrix.member }}

      - name: Lint / Docs
        run: pnpm lint:docs ${{ matrix.member }}

      - name: Lint / Features
        run: pnpm lint:features ${{ matrix.member }}

      - name: Build (sbf)
        run: pnpm build ${{ matrix.member }}

      - name: Test
        run: pnpm test ${{ matrix.member }}
